// Generated by scripts/generate-splash-screens.mjs — do not edit by hand.
export const APPLE_SPLASH_SCREENS: { url: string; media: string }[] = [
	{
		"url": "/icons/splash/iphone-16-pro-max-portrait.png",
		"media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/iphone-16-pro-max-landscape.png",
		"media": "(device-width: 430px) and (device-height: 932px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/iphone-16-pro-portrait.png",
		"media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/iphone-16-pro-landscape.png",
		"media": "(device-width: 393px) and (device-height: 852px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/iphone-16-portrait.png",
		"media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/iphone-16-landscape.png",
		"media": "(device-width: 390px) and (device-height: 844px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/iphone-16-plus-portrait.png",
		"media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/iphone-16-plus-landscape.png",
		"media": "(device-width: 428px) and (device-height: 926px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/iphone-13-mini-portrait.png",
		"media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/iphone-13-mini-landscape.png",
		"media": "(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/iphone-11-portrait.png",
		"media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/iphone-11-landscape.png",
		"media": "(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/iphone-se-portrait.png",
		"media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/iphone-se-landscape.png",
		"media": "(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/ipad-10-portrait.png",
		"media": "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/ipad-10-landscape.png",
		"media": "(device-width: 810px) and (device-height: 1080px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/ipad-pro-11-portrait.png",
		"media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/ipad-pro-11-landscape.png",
		"media": "(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
	},
	{
		"url": "/icons/splash/ipad-pro-12-9-portrait.png",
		"media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: portrait)"
	},
	{
		"url": "/icons/splash/ipad-pro-12-9-landscape.png",
		"media": "(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2) and (orientation: landscape)"
	}
];
